### ISSUE TITLE
Made a fork for mobile phones

### ISSUE THREAD

**Issue by Nthompson096** [vin3110/facecheck.id-results-extractor#2]
[Mobile friendly UI on mobile phones](https://github.com/Nthompson096/facecheck.id-results-extractor-mobile/blob/main/facecheck-url-extractor-mobile.user.js) Figured I'd share with you, hate having to switch on desktop mode on my android device.

**Comment by vin3110** [comment]
Thanks! I'm unavailable till the 29th but I'll try to incorporate a mobile UI for android into the main script if possible :)

**Comment by Nthompson096** [comment]
Hey man no problem! much more user friendly anyhow.

**Comment by Nthompson096** [comment]
[Created a desktop and mobile version of the script ](https://github.com/Nthompson096/facecheck.id-results-extractor-mobile/blob/main/FaceCheck%20URL%20Extractor%20with%20Ratings%20(Desktop%20and%20Mobile)-2.1.0.user.js) cheers
